// Mocks generated by Mockito 5.4.6 from annotations
// in app_client/test/widgets/client_form_site_address_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i7;

import 'package:app_client/src/models/client.dart' as _i3;
import 'package:app_client/src/models/item.dart' as _i5;
import 'package:app_client/src/models/rectangle.dart' as _i6;
import 'package:app_client/src/providers/client_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ClientProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientProvider extends _i1.Mock implements _i2.ClientProvider {
  MockClientProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Client> get clients => (super.noSuchMethod(
        Invocation.getter(#clients),
        returnValue: <_i3.Client>[],
      ) as List<_i3.Client>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> loadClients() => (super.noSuchMethod(
        Invocation.method(
          #loadClients,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addClient(_i3.Client? client) => (super.noSuchMethod(
        Invocation.method(
          #addClient,
          [client],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateClient(_i3.Client? client) => (super.noSuchMethod(
        Invocation.method(
          #updateClient,
          [client],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteClient(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #deleteClient,
          [localId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> addItem(_i5.Item? item) => (super.noSuchMethod(
        Invocation.method(
          #addItem,
          [item],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<_i5.Item?> getItemByLocalId(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #getItemByLocalId,
          [localId],
        ),
        returnValue: _i4.Future<_i5.Item?>.value(),
      ) as _i4.Future<_i5.Item?>);

  @override
  _i4.Future<void> updateItem(_i5.Item? item) => (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [item],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteItem(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [localId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addRectangle(_i6.Rectangle? rectangle) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRectangle,
          [rectangle],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateRectangle(_i6.Rectangle? rectangle) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRectangle,
          [rectangle],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRectangle(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRectangle,
          [localId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> applyBulkPrice(
    int? clientLocalId,
    double? price,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyBulkPrice,
          [
            clientLocalId,
            price,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
