// Mocks generated by Mockito 5.4.6 from annotations
// in app_client/test/widgets/keyboard_dismissal_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app_client/src/models/client.dart' as _i5;
import 'package:app_client/src/models/default_price.dart' as _i8;
import 'package:app_client/src/models/item.dart' as _i6;
import 'package:app_client/src/models/rectangle.dart' as _i7;
import 'package:app_client/src/services/db_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DbService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDbService extends _i1.Mock implements _i3.DbService {
  MockDbService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i4.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i4.Future<_i2.Database>);

  @override
  _i4.Future<int> insertClient(_i5.Client? client) => (super.noSuchMethod(
        Invocation.method(
          #insertClient,
          [client],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.Client>> getClients() => (super.noSuchMethod(
        Invocation.method(
          #getClients,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Client>>.value(<_i5.Client>[]),
      ) as _i4.Future<List<_i5.Client>>);

  @override
  _i4.Future<_i5.Client?> getClientByRemoteId(String? remoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClientByRemoteId,
          [remoteId],
        ),
        returnValue: _i4.Future<_i5.Client?>.value(),
      ) as _i4.Future<_i5.Client?>);

  @override
  _i4.Future<int> updateClient(_i5.Client? client) => (super.noSuchMethod(
        Invocation.method(
          #updateClient,
          [client],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> softDeleteClient(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #softDeleteClient,
          [localId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> insertItem(_i6.Item? item) => (super.noSuchMethod(
        Invocation.method(
          #insertItem,
          [item],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i6.Item>> getItemsByClientId(int? clientId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsByClientId,
          [clientId],
        ),
        returnValue: _i4.Future<List<_i6.Item>>.value(<_i6.Item>[]),
      ) as _i4.Future<List<_i6.Item>>);

  @override
  _i4.Future<_i6.Item?> getItemByRemoteId(String? remoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemByRemoteId,
          [remoteId],
        ),
        returnValue: _i4.Future<_i6.Item?>.value(),
      ) as _i4.Future<_i6.Item?>);

  @override
  _i4.Future<_i6.Item?> getItemByLocalId(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #getItemByLocalId,
          [localId],
        ),
        returnValue: _i4.Future<_i6.Item?>.value(),
      ) as _i4.Future<_i6.Item?>);

  @override
  _i4.Future<int> updateItem(_i6.Item? item) => (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [item],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> softDeleteItem(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #softDeleteItem,
          [localId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> insertRectangle(_i7.Rectangle? rectangle) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertRectangle,
          [rectangle],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i7.Rectangle>> getRectanglesByItemId(int? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRectanglesByItemId,
          [itemId],
        ),
        returnValue: _i4.Future<List<_i7.Rectangle>>.value(<_i7.Rectangle>[]),
      ) as _i4.Future<List<_i7.Rectangle>>);

  @override
  _i4.Future<_i7.Rectangle?> getRectangleByRemoteId(String? remoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRectangleByRemoteId,
          [remoteId],
        ),
        returnValue: _i4.Future<_i7.Rectangle?>.value(),
      ) as _i4.Future<_i7.Rectangle?>);

  @override
  _i4.Future<int> updateRectangle(_i7.Rectangle? rectangle) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRectangle,
          [rectangle],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> softDeleteRectangle(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #softDeleteRectangle,
          [localId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> insertDefaultPrice(_i8.DefaultPrice? defaultPrice) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertDefaultPrice,
          [defaultPrice],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i8.DefaultPrice>> getDefaultPrices() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultPrices,
          [],
        ),
        returnValue:
            _i4.Future<List<_i8.DefaultPrice>>.value(<_i8.DefaultPrice>[]),
      ) as _i4.Future<List<_i8.DefaultPrice>>);

  @override
  _i4.Future<int> updateDefaultPrice(_i8.DefaultPrice? defaultPrice) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDefaultPrice,
          [defaultPrice],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> deleteDefaultPrice(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #deleteDefaultPrice,
          [localId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.Client>> getDirtyClients() => (super.noSuchMethod(
        Invocation.method(
          #getDirtyClients,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Client>>.value(<_i5.Client>[]),
      ) as _i4.Future<List<_i5.Client>>);

  @override
  _i4.Future<List<_i6.Item>> getDirtyItems() => (super.noSuchMethod(
        Invocation.method(
          #getDirtyItems,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Item>>.value(<_i6.Item>[]),
      ) as _i4.Future<List<_i6.Item>>);

  @override
  _i4.Future<List<_i7.Rectangle>> getDirtyRectangles() => (super.noSuchMethod(
        Invocation.method(
          #getDirtyRectangles,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Rectangle>>.value(<_i7.Rectangle>[]),
      ) as _i4.Future<List<_i7.Rectangle>>);

  @override
  _i4.Future<List<_i8.DefaultPrice>> getDirtyDefaultPrices() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDirtyDefaultPrices,
          [],
        ),
        returnValue:
            _i4.Future<List<_i8.DefaultPrice>>.value(<_i8.DefaultPrice>[]),
      ) as _i4.Future<List<_i8.DefaultPrice>>);

  @override
  _i4.Future<void> markAsSynced(
    String? table,
    String? remoteId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [
            table,
            remoteId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
