// Mocks generated by Mockito 5.4.6 from annotations
// in app_client/test/unit/auth_provider_franchisee_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:app_client/src/models/warranty.dart' as _i2;
import 'package:app_client/src/services/api_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWarranty_0 extends _i1.SmartFake implements _i2.Warranty {
  _FakeWarranty_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  void setToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<Map<String, dynamic>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> sync(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #sync,
          [data],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i2.Warranty> uploadWarranty(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadWarranty,
          [data],
        ),
        returnValue: _i5.Future<_i2.Warranty>.value(_FakeWarranty_0(
          this,
          Invocation.method(
            #uploadWarranty,
            [data],
          ),
        )),
      ) as _i5.Future<_i2.Warranty>);

  @override
  _i5.Future<List<_i2.Warranty>> getWarranties(String? clientId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWarranties,
          [clientId],
        ),
        returnValue: _i5.Future<List<_i2.Warranty>>.value(<_i2.Warranty>[]),
      ) as _i5.Future<List<_i2.Warranty>>);
}
