// Mocks generated by Mockito 5.4.6 from annotations
// in app_client/test/unit/sync_service_full_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:app_client/src/models/client.dart' as _i7;
import 'package:app_client/src/models/default_price.dart' as _i10;
import 'package:app_client/src/models/item.dart' as _i8;
import 'package:app_client/src/models/proposal.dart' as _i13;
import 'package:app_client/src/models/rectangle.dart' as _i9;
import 'package:app_client/src/models/warranty.dart' as _i11;
import 'package:app_client/src/models/warranty_deletion_tombstone.dart' as _i12;
import 'package:app_client/src/services/api_service.dart' as _i3;
import 'package:app_client/src/services/db_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get serverUrl => (super.noSuchMethod(
        Invocation.getter(#serverUrl),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#serverUrl),
        ),
      ) as String);

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  Map<String, String> get authenticatedHeaders => (super.noSuchMethod(
        Invocation.getter(#authenticatedHeaders),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  void setToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> loadServerUrl() => (super.noSuchMethod(
        Invocation.method(
          #loadServerUrl,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setServerUrl(String? serverUrl) => (super.noSuchMethod(
        Invocation.method(
          #setServerUrl,
          [serverUrl],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  String resolveUrl(String? pathOrUrl) => (super.noSuchMethod(
        Invocation.method(
          #resolveUrl,
          [pathOrUrl],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #resolveUrl,
            [pathOrUrl],
          ),
        ),
      ) as String);

  @override
  String? resolveProtectedClientPhotoUrl(String? photoUrl) =>
      (super.noSuchMethod(Invocation.method(
        #resolveProtectedClientPhotoUrl,
        [photoUrl],
      )) as String?);

  @override
  _i5.Future<Map<String, dynamic>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> sync(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #sync,
          [data],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> syncV2(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncV2,
          [data],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> uploadWarranty(
    String? filePath,
    Map<String, String>? fields, {
    String? idempotencyKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadWarranty,
          [
            filePath,
            fields,
          ],
          {#idempotencyKey: idempotencyKey},
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> deleteWarranty({
    required String? id,
    required String? warrantyCardNumber,
    required int? warrantyVersion,
    required String? irreversibleConfirmation,
    required String? idempotencyKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWarranty,
          [],
          {
            #id: id,
            #warrantyCardNumber: warrantyCardNumber,
            #warrantyVersion: warrantyVersion,
            #irreversibleConfirmation: irreversibleConfirmation,
            #idempotencyKey: idempotencyKey,
          },
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> uploadProposal(
    String? filePath,
    Map<String, String>? fields,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProposal,
          [
            filePath,
            fields,
          ],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> deleteProposal(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProposal,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> uploadClientPhoto(
    String? clientId,
    String? filePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadClientPhoto,
          [
            clientId,
            filePath,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #uploadClientPhoto,
            [
              clientId,
              filePath,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> deleteClientPhoto(String? photoUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteClientPhoto,
          [photoUrl],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [DbService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDbService extends _i1.Mock implements _i6.DbService {
  MockDbService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i5.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i5.Future<_i2.Database>);

  @override
  _i5.Future<int> insertClient(_i7.Client? client) => (super.noSuchMethod(
        Invocation.method(
          #insertClient,
          [client],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i7.Client>> getClients() => (super.noSuchMethod(
        Invocation.method(
          #getClients,
          [],
        ),
        returnValue: _i5.Future<List<_i7.Client>>.value(<_i7.Client>[]),
      ) as _i5.Future<List<_i7.Client>>);

  @override
  _i5.Future<_i7.Client?> getClientByRemoteId(String? remoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClientByRemoteId,
          [remoteId],
        ),
        returnValue: _i5.Future<_i7.Client?>.value(),
      ) as _i5.Future<_i7.Client?>);

  @override
  _i5.Future<int> updateClient(_i7.Client? client) => (super.noSuchMethod(
        Invocation.method(
          #updateClient,
          [client],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> softDeleteClient(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #softDeleteClient,
          [localId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> insertItem(_i8.Item? item) => (super.noSuchMethod(
        Invocation.method(
          #insertItem,
          [item],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i8.Item>> getItemsByClientId(int? clientId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsByClientId,
          [clientId],
        ),
        returnValue: _i5.Future<List<_i8.Item>>.value(<_i8.Item>[]),
      ) as _i5.Future<List<_i8.Item>>);

  @override
  _i5.Future<_i8.Item?> getItemByRemoteId(String? remoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemByRemoteId,
          [remoteId],
        ),
        returnValue: _i5.Future<_i8.Item?>.value(),
      ) as _i5.Future<_i8.Item?>);

  @override
  _i5.Future<_i8.Item?> getItemByLocalId(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #getItemByLocalId,
          [localId],
        ),
        returnValue: _i5.Future<_i8.Item?>.value(),
      ) as _i5.Future<_i8.Item?>);

  @override
  _i5.Future<int> updateItem(_i8.Item? item) => (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [item],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> softDeleteItem(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #softDeleteItem,
          [localId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> insertRectangle(_i9.Rectangle? rectangle) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertRectangle,
          [rectangle],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i9.Rectangle>> getRectanglesByItemId(int? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRectanglesByItemId,
          [itemId],
        ),
        returnValue: _i5.Future<List<_i9.Rectangle>>.value(<_i9.Rectangle>[]),
      ) as _i5.Future<List<_i9.Rectangle>>);

  @override
  _i5.Future<_i9.Rectangle?> getRectangleByRemoteId(String? remoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRectangleByRemoteId,
          [remoteId],
        ),
        returnValue: _i5.Future<_i9.Rectangle?>.value(),
      ) as _i5.Future<_i9.Rectangle?>);

  @override
  _i5.Future<int> updateRectangle(_i9.Rectangle? rectangle) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRectangle,
          [rectangle],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> softDeleteRectangle(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #softDeleteRectangle,
          [localId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> claimLegacyDefaultPrices(String? franchiseeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #claimLegacyDefaultPrices,
          [franchiseeId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> insertDefaultPrice(
    _i10.DefaultPrice? defaultPrice, {
    required String? franchiseeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertDefaultPrice,
          [defaultPrice],
          {#franchiseeId: franchiseeId},
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i10.DefaultPrice>> getDefaultPrices(String? franchiseeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDefaultPrices,
          [franchiseeId],
        ),
        returnValue:
            _i5.Future<List<_i10.DefaultPrice>>.value(<_i10.DefaultPrice>[]),
      ) as _i5.Future<List<_i10.DefaultPrice>>);

  @override
  _i5.Future<int> updateDefaultPrice(
    _i10.DefaultPrice? defaultPrice, {
    required String? franchiseeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDefaultPrice,
          [defaultPrice],
          {#franchiseeId: franchiseeId},
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> deleteDefaultPrice(
    int? localId, {
    required String? franchiseeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDefaultPrice,
          [localId],
          {#franchiseeId: franchiseeId},
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> insertWarranty(_i11.Warranty? warranty) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWarranty,
          [warranty],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i11.Warranty>> getWarrantiesByClientId(int? clientId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWarrantiesByClientId,
          [clientId],
        ),
        returnValue: _i5.Future<List<_i11.Warranty>>.value(<_i11.Warranty>[]),
      ) as _i5.Future<List<_i11.Warranty>>);

  @override
  _i5.Future<_i11.Warranty?> getWarrantyByRemoteId(String? remoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWarrantyByRemoteId,
          [remoteId],
        ),
        returnValue: _i5.Future<_i11.Warranty?>.value(),
      ) as _i5.Future<_i11.Warranty?>);

  @override
  _i5.Future<int> updateWarranty(_i11.Warranty? warranty) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWarranty,
          [warranty],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> hardDeleteWarranty(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #hardDeleteWarranty,
          [localId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> hardDeleteWarrantyByRemoteId(String? remoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #hardDeleteWarrantyByRemoteId,
          [remoteId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> replaceWarrantyFromServer(_i11.Warranty? warranty) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWarrantyFromServer,
          [warranty],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> applyWarrantyFromServerIfUnchanged(
    _i11.Warranty? warranty, {
    required String? submittedUpdatedAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyWarrantyFromServerIfUnchanged,
          [warranty],
          {#submittedUpdatedAt: submittedUpdatedAt},
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> applyWarrantyTombstone(
          _i12.WarrantyDeletionTombstone? tombstone) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyWarrantyTombstone,
          [tombstone],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> getWarrantyTombstoneCursor(String? franchiseeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWarrantyTombstoneCursor,
          [franchiseeId],
        ),
        returnValue: _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getWarrantyTombstoneCursor,
            [franchiseeId],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> applyWarrantyTombstonesAndCursor(
    List<_i12.WarrantyDeletionTombstone>? tombstones, {
    required String? franchiseeId,
    required String? cursor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyWarrantyTombstonesAndCursor,
          [tombstones],
          {
            #franchiseeId: franchiseeId,
            #cursor: cursor,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> hasWarrantyTombstone(
    String? warrantyId, {
    required String? franchiseeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasWarrantyTombstone,
          [warrantyId],
          {#franchiseeId: franchiseeId},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> insertProposal(_i13.Proposal? proposal) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertProposal,
          [proposal],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i13.Proposal>> getProposalsByClientId(int? clientId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProposalsByClientId,
          [clientId],
        ),
        returnValue: _i5.Future<List<_i13.Proposal>>.value(<_i13.Proposal>[]),
      ) as _i5.Future<List<_i13.Proposal>>);

  @override
  _i5.Future<_i13.Proposal?> getProposalByRemoteId(String? remoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProposalByRemoteId,
          [remoteId],
        ),
        returnValue: _i5.Future<_i13.Proposal?>.value(),
      ) as _i5.Future<_i13.Proposal?>);

  @override
  _i5.Future<int> updateProposal(_i13.Proposal? proposal) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProposal,
          [proposal],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> softDeleteProposal(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #softDeleteProposal,
          [localId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> isSyncV2Enabled(String? franchiseeId) => (super.noSuchMethod(
        Invocation.method(
          #isSyncV2Enabled,
          [franchiseeId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> supportsSyncV2() => (super.noSuchMethod(
        Invocation.method(
          #supportsSyncV2,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<String> getSyncV2Cursor(String? franchiseeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncV2Cursor,
          [franchiseeId],
        ),
        returnValue: _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getSyncV2Cursor,
            [franchiseeId],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<Map<String, List<Map<String, dynamic>>>> getPendingLwwChanges(
          String? franchiseeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingLwwChanges,
          [franchiseeId],
        ),
        returnValue: _i5.Future<Map<String, List<Map<String, dynamic>>>>.value(
            <String, List<Map<String, dynamic>>>{}),
      ) as _i5.Future<Map<String, List<Map<String, dynamic>>>>);

  @override
  _i5.Future<void> applySyncV2Response({
    required String? franchiseeId,
    required String? responseCursor,
    required String? warrantyTombstoneCursor,
    required Map<String, List<Map<String, dynamic>>>? records,
    required List<_i12.WarrantyDeletionTombstone>? warrantyTombstones,
    required Map<String, Map<String, String>>? submittedChangeIds,
    required Map<String, String>? outcomeStatuses,
    required bool? activateProtocol,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #applySyncV2Response,
          [],
          {
            #franchiseeId: franchiseeId,
            #responseCursor: responseCursor,
            #warrantyTombstoneCursor: warrantyTombstoneCursor,
            #records: records,
            #warrantyTombstones: warrantyTombstones,
            #submittedChangeIds: submittedChangeIds,
            #outcomeStatuses: outcomeStatuses,
            #activateProtocol: activateProtocol,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.Client>> getDirtyClients() => (super.noSuchMethod(
        Invocation.method(
          #getDirtyClients,
          [],
        ),
        returnValue: _i5.Future<List<_i7.Client>>.value(<_i7.Client>[]),
      ) as _i5.Future<List<_i7.Client>>);

  @override
  _i5.Future<List<_i8.Item>> getDirtyItems() => (super.noSuchMethod(
        Invocation.method(
          #getDirtyItems,
          [],
        ),
        returnValue: _i5.Future<List<_i8.Item>>.value(<_i8.Item>[]),
      ) as _i5.Future<List<_i8.Item>>);

  @override
  _i5.Future<List<_i9.Rectangle>> getDirtyRectangles() => (super.noSuchMethod(
        Invocation.method(
          #getDirtyRectangles,
          [],
        ),
        returnValue: _i5.Future<List<_i9.Rectangle>>.value(<_i9.Rectangle>[]),
      ) as _i5.Future<List<_i9.Rectangle>>);

  @override
  _i5.Future<List<_i10.DefaultPrice>> getDirtyDefaultPrices(
          String? franchiseeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDirtyDefaultPrices,
          [franchiseeId],
        ),
        returnValue:
            _i5.Future<List<_i10.DefaultPrice>>.value(<_i10.DefaultPrice>[]),
      ) as _i5.Future<List<_i10.DefaultPrice>>);

  @override
  _i5.Future<_i10.DefaultPrice?> getDefaultPriceByRemoteId(
    String? remoteId,
    String? franchiseeId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDefaultPriceByRemoteId,
          [
            remoteId,
            franchiseeId,
          ],
        ),
        returnValue: _i5.Future<_i10.DefaultPrice?>.value(),
      ) as _i5.Future<_i10.DefaultPrice?>);

  @override
  _i5.Future<List<_i11.Warranty>> getDirtyWarranties() => (super.noSuchMethod(
        Invocation.method(
          #getDirtyWarranties,
          [],
        ),
        returnValue: _i5.Future<List<_i11.Warranty>>.value(<_i11.Warranty>[]),
      ) as _i5.Future<List<_i11.Warranty>>);

  @override
  _i5.Future<List<_i13.Proposal>> getDirtyProposals() => (super.noSuchMethod(
        Invocation.method(
          #getDirtyProposals,
          [],
        ),
        returnValue: _i5.Future<List<_i13.Proposal>>.value(<_i13.Proposal>[]),
      ) as _i5.Future<List<_i13.Proposal>>);

  @override
  _i5.Future<int> markAsSynced(
    String? table,
    String? remoteId, {
    String? franchiseeId,
    required String? submittedUpdatedAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [
            table,
            remoteId,
          ],
          {
            #franchiseeId: franchiseeId,
            #submittedUpdatedAt: submittedUpdatedAt,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
}
