// Mocks generated by Mockito 5.4.6 from annotations
// in app_client/test/unit/sync_service_full_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:app_client/src/models/client.dart' as _i8;
import 'package:app_client/src/models/default_price.dart' as _i11;
import 'package:app_client/src/models/item.dart' as _i9;
import 'package:app_client/src/models/rectangle.dart' as _i10;
import 'package:app_client/src/models/warranty.dart' as _i2;
import 'package:app_client/src/services/api_service.dart' as _i4;
import 'package:app_client/src/services/db_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:sqflite/sqflite.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWarranty_0 extends _i1.SmartFake implements _i2.Warranty {
  _FakeWarranty_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  void setToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<Map<String, dynamic>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> sync(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #sync,
          [data],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i2.Warranty> uploadWarranty(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadWarranty,
          [data],
        ),
        returnValue: _i6.Future<_i2.Warranty>.value(_FakeWarranty_0(
          this,
          Invocation.method(
            #uploadWarranty,
            [data],
          ),
        )),
      ) as _i6.Future<_i2.Warranty>);

  @override
  _i6.Future<List<_i2.Warranty>> getWarranties(String? clientId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWarranties,
          [clientId],
        ),
        returnValue: _i6.Future<List<_i2.Warranty>>.value(<_i2.Warranty>[]),
      ) as _i6.Future<List<_i2.Warranty>>);
}

/// A class which mocks [DbService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDbService extends _i1.Mock implements _i7.DbService {
  MockDbService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i6.Future<_i3.Database>.value(_FakeDatabase_1(
          this,
          Invocation.getter(#database),
        )),
      ) as _i6.Future<_i3.Database>);

  @override
  _i6.Future<int> insertClient(_i8.Client? client) => (super.noSuchMethod(
        Invocation.method(
          #insertClient,
          [client],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i8.Client>> getClients() => (super.noSuchMethod(
        Invocation.method(
          #getClients,
          [],
        ),
        returnValue: _i6.Future<List<_i8.Client>>.value(<_i8.Client>[]),
      ) as _i6.Future<List<_i8.Client>>);

  @override
  _i6.Future<_i8.Client?> getClientByRemoteId(String? remoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClientByRemoteId,
          [remoteId],
        ),
        returnValue: _i6.Future<_i8.Client?>.value(),
      ) as _i6.Future<_i8.Client?>);

  @override
  _i6.Future<int> updateClient(_i8.Client? client) => (super.noSuchMethod(
        Invocation.method(
          #updateClient,
          [client],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> softDeleteClient(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #softDeleteClient,
          [localId],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> insertItem(_i9.Item? item) => (super.noSuchMethod(
        Invocation.method(
          #insertItem,
          [item],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i9.Item>> getItemsByClientId(int? clientId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsByClientId,
          [clientId],
        ),
        returnValue: _i6.Future<List<_i9.Item>>.value(<_i9.Item>[]),
      ) as _i6.Future<List<_i9.Item>>);

  @override
  _i6.Future<_i9.Item?> getItemByRemoteId(String? remoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemByRemoteId,
          [remoteId],
        ),
        returnValue: _i6.Future<_i9.Item?>.value(),
      ) as _i6.Future<_i9.Item?>);

  @override
  _i6.Future<_i9.Item?> getItemByLocalId(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #getItemByLocalId,
          [localId],
        ),
        returnValue: _i6.Future<_i9.Item?>.value(),
      ) as _i6.Future<_i9.Item?>);

  @override
  _i6.Future<int> updateItem(_i9.Item? item) => (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [item],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> softDeleteItem(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #softDeleteItem,
          [localId],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> insertRectangle(_i10.Rectangle? rectangle) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertRectangle,
          [rectangle],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i10.Rectangle>> getRectanglesByItemId(int? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRectanglesByItemId,
          [itemId],
        ),
        returnValue: _i6.Future<List<_i10.Rectangle>>.value(<_i10.Rectangle>[]),
      ) as _i6.Future<List<_i10.Rectangle>>);

  @override
  _i6.Future<_i10.Rectangle?> getRectangleByRemoteId(String? remoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRectangleByRemoteId,
          [remoteId],
        ),
        returnValue: _i6.Future<_i10.Rectangle?>.value(),
      ) as _i6.Future<_i10.Rectangle?>);

  @override
  _i6.Future<int> updateRectangle(_i10.Rectangle? rectangle) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRectangle,
          [rectangle],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> softDeleteRectangle(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #softDeleteRectangle,
          [localId],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> insertDefaultPrice(_i11.DefaultPrice? defaultPrice) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertDefaultPrice,
          [defaultPrice],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i11.DefaultPrice>> getDefaultPrices() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultPrices,
          [],
        ),
        returnValue:
            _i6.Future<List<_i11.DefaultPrice>>.value(<_i11.DefaultPrice>[]),
      ) as _i6.Future<List<_i11.DefaultPrice>>);

  @override
  _i6.Future<int> updateDefaultPrice(_i11.DefaultPrice? defaultPrice) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDefaultPrice,
          [defaultPrice],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> deleteDefaultPrice(int? localId) => (super.noSuchMethod(
        Invocation.method(
          #deleteDefaultPrice,
          [localId],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i8.Client>> getDirtyClients() => (super.noSuchMethod(
        Invocation.method(
          #getDirtyClients,
          [],
        ),
        returnValue: _i6.Future<List<_i8.Client>>.value(<_i8.Client>[]),
      ) as _i6.Future<List<_i8.Client>>);

  @override
  _i6.Future<List<_i9.Item>> getDirtyItems() => (super.noSuchMethod(
        Invocation.method(
          #getDirtyItems,
          [],
        ),
        returnValue: _i6.Future<List<_i9.Item>>.value(<_i9.Item>[]),
      ) as _i6.Future<List<_i9.Item>>);

  @override
  _i6.Future<List<_i10.Rectangle>> getDirtyRectangles() => (super.noSuchMethod(
        Invocation.method(
          #getDirtyRectangles,
          [],
        ),
        returnValue: _i6.Future<List<_i10.Rectangle>>.value(<_i10.Rectangle>[]),
      ) as _i6.Future<List<_i10.Rectangle>>);

  @override
  _i6.Future<List<_i11.DefaultPrice>> getDirtyDefaultPrices() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDirtyDefaultPrices,
          [],
        ),
        returnValue:
            _i6.Future<List<_i11.DefaultPrice>>.value(<_i11.DefaultPrice>[]),
      ) as _i6.Future<List<_i11.DefaultPrice>>);

  @override
  _i6.Future<void> markAsSynced(
    String? table,
    String? remoteId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [
            table,
            remoteId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
