#!/usr/bin/env node
'use strict';
const fs = require('node:fs/promises');
const path = require('node:path');
const { buildManifest, LocalReleaseTarget, publishToLocalFixture, readLedger, recoverLedgerLock, recoverPublication, resolveRecoveryGuard, reserveVersionCodeAtPath, secureLedgerAndRoot } = require('./lib.cjs');

function usage() { return 'Usage: publish.cjs reserve|publish|recover|recover-lock|resolve-recovery-guard --environment staging|production --ledger FILE --fixture-root DIR --origin HTTPS_ORIGIN [--dry-run]. Available publish also requires --artifact, --tool-manifest, and --receipt-at. recover-lock requires --lock-recovery-receipt. resolve-recovery-guard requires --guard-nonce and --acknowledge RESOLVE-RECOVERY-GUARD. This tool is local-fixture only.'; }
function args(argv) { const [command, ...rest] = argv; const values = { command }; for (let index = 0; index < rest.length; index += 1) { const token = rest[index]; if (!token.startsWith('--')) throw new Error(`unexpected argument ${token}`); const key = token.slice(2).replace(/-([a-z])/g, (_, letter) => letter.toUpperCase()); if (key === 'dryRun') { values[key] = true; continue; } const value = rest[++index]; if (!value || value.startsWith('--')) throw new Error(`${token} requires a value`); values[key] = value; } return values; }
function integer(value, field) { const parsed = Number(value); if (!Number.isInteger(parsed)) throw new Error(`${field} must be an integer`); return parsed; }
async function requireReceipt(filePath, field) { if (!filePath) return undefined; const stat = await fs.stat(filePath).catch(() => null); if (!stat || !stat.isFile() || stat.isSymbolicLink() || stat.size === 0) throw new Error(`${field} must name a non-empty local non-symlink receipt file`); return path.resolve(filePath); }
async function main() {
  const options = args(process.argv.slice(2));
  if (!['reserve', 'publish', 'recover', 'recover-lock', 'resolve-recovery-guard'].includes(options.command) || !['staging', 'production'].includes(options.environment) || !options.ledger || !options.fixtureRoot || !options.origin) throw new Error(usage());
  const secure = await secureLedgerAndRoot(options.ledger, options.fixtureRoot); const lockOptions = {};
  if (options.command === 'reserve') { const next = await reserveVersionCodeAtPath({ ledgerPath: secure.ledgerPath, environment: options.environment, root: secure.root, origin: options.origin, code: integer(options.versionCode, 'version code'), dryRun: Boolean(options.dryRun), lockOptions }); process.stdout.write(`${JSON.stringify({ action: 'reserve-version-code', environment: options.environment, dryRun: Boolean(options.dryRun), reservedVersionCodes: next.reservedVersionCodes }, null, 2)}\n`); return; }
  if (options.command === 'recover-lock') { const quarantined = await recoverLedgerLock(secure.ledgerPath, options.lockRecoveryReceipt && path.resolve(options.lockRecoveryReceipt)); process.stdout.write(`${JSON.stringify({ action: 'recovered-lock', quarantined }, null, 2)}\n`); return; }
  if (options.command === 'resolve-recovery-guard') { const result = await resolveRecoveryGuard({ ledgerPath: secure.ledgerPath, guardNonce: options.guardNonce, acknowledgement: options.acknowledge }); process.stdout.write(`${JSON.stringify({ action: 'resolved-recovery-guard', ...result }, null, 2)}\n`); return; }
  const target = new LocalReleaseTarget(secure.root);
  if (options.command === 'recover') { const result = await recoverPublication({ target, ledgerPath: secure.ledgerPath, environment: options.environment, root: secure.root, origin: options.origin, receiptPath: options.receipt && path.resolve(options.receipt), lockOptions }); process.stdout.write(`${JSON.stringify(result.receipt, null, 2)}\n`); return; }
  if (!options.type || !options.revision || !options.publishedAt || !options.receiptAt) throw new Error(usage());
  const ledger = await readLedger(secure.ledgerPath, options.environment, secure.root, options.origin);
  const manifest = buildManifest({ environment: options.environment, ledger, type: options.type, revision: integer(options.revision, 'revision'), publishedAt: options.publishedAt, origin: options.origin, version: options.version, versionCode: options.versionCode === undefined ? undefined : integer(options.versionCode, 'version code'), minimumSupportedVersionCode: options.minimumSupportedVersionCode === undefined ? undefined : integer(options.minimumSupportedVersionCode, 'minimum supported version code'), sha256: options.sha256, sizeBytes: options.sizeBytes === undefined ? undefined : integer(options.sizeBytes, 'size bytes'), releaseNotes: options.releaseNotes, requiredUpdateReason: options.requiredUpdateReason, reason: options.reason });
  const result = await publishToLocalFixture({ target, ledgerPath: secure.ledgerPath, environment: options.environment, root: secure.root, origin: options.origin, manifest, artifactPath: options.artifact && path.resolve(options.artifact), toolManifestPath: options.toolManifest && path.resolve(options.toolManifest), receiptPath: options.receipt && path.resolve(options.receipt), trustedReceiptAt: options.receiptAt, dryRun: Boolean(options.dryRun), lockOptions, approval: options.approval, signingBackupReceipt: await requireReceipt(options.signingBackupReceipt, 'signing backup receipt'), pilotReceipt: await requireReceipt(options.pilotReceipt, 'pilot receipt'), dependencyReceipt: await requireReceipt(options.dependencyReceipt, 'dependency receipt') });
  process.stdout.write(`${JSON.stringify(result.receipt, null, 2)}\n`);
}
main().catch((error) => { process.stderr.write(`update publishing refused: ${error.message}\n`); process.exitCode = 1; });
