'use strict';
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const { spawn } = require('node:child_process');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const { test: nodeTest } = require('node:test');
function test(name, ...args) { return nodeTest(name, ...args); }
const { PACKAGE_IDS, LocalReleaseTarget, basicArtifactMetadata, buildManifest, canonicalManifestIdentity, emptyLedger, publishToLocalFixture, readLedger, recoverLedgerLock, recoverPublication, resolveRecoveryGuard, reserveVersionCodeAtPath, verifyApkArtifact, withLedgerLock } = require('../lib.cjs');
const origin = 'https://staging.example.test'; const time = '2026-07-30T12:00:00Z';
async function fixture() { const root = await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(), 'damsure-publish-'))); return { root, remote: path.join(root, 'remote'), ledgerPath: path.join(root, 'ledger.json') }; }
async function fakeTools(root) { const aapt = path.join(root, 'aapt'); const apksigner = path.join(root, 'apksigner'); const stagingCertificate = 'AA'.repeat(32); const productionCertificate = 'BB'.repeat(32); await fs.writeFile(aapt, "#!/usr/bin/env node\nconsole.log(\"package: name='com.dryspotuppala.staging' versionCode='2' versionName='1.0.2'\")\n"); await fs.writeFile(apksigner, `#!/usr/bin/env node\nconsole.log('Signer #1 certificate SHA-256 digest: ${stagingCertificate}')\n`); await fs.chmod(aapt, 0o755); await fs.chmod(apksigner, 0o755); const hash = async (file) => crypto.createHash('sha256').update(await fs.readFile(file)).digest('hex'); const toolManifest = path.join(root, 'tool-manifest.json'); await fs.writeFile(toolManifest, `${JSON.stringify({ schemaVersion: 1, tools: { aapt: { path: aapt, sha256: await hash(aapt) }, apksigner: { path: apksigner, sha256: await hash(apksigner) } }, certificates: { production: productionCertificate, staging: stagingCertificate } })}\n`, { mode: 0o600 }); return { aapt, apksigner, toolManifest, stagingCertificate, productionCertificate }; }
async function candidate(root) { const artifact = path.join(root, 'candidate.apk'); await fs.writeFile(artifact, Buffer.concat([Buffer.from([0x50, 0x4b, 0x03, 0x04]), Buffer.from('fixture')])); return { artifact, ...(await basicArtifactMetadata(artifact, { requireApkZip: true })) }; }
async function prepared(code = 2) { const f = await fixture(); const ledger = await reserveVersionCodeAtPath({ ledgerPath: f.ledgerPath, environment: 'staging', root: f.remote, origin, code }); const file = await candidate(f.root); const manifest = buildManifest({ environment: 'staging', ledger, type: 'available', revision: 1, publishedAt: time, origin, version: '1.0.2', versionCode: code, minimumSupportedVersionCode: 1, sha256: file.sha256, sizeBytes: file.sizeBytes, releaseNotes: 'Notes.', requiredUpdateReason: 'Required.' }); return { ...f, ledger, ...file, manifest, tools: await fakeTools(f.root) }; }
function publishArgs(state, extra = {}) { return { target: new LocalReleaseTarget(state.remote), ledgerPath: state.ledgerPath, environment: 'staging', root: state.remote, origin, manifest: state.manifest, artifactPath: state.artifact, toolManifestPath: state.tools.toolManifest, trustedReceiptAt: time, ...extra }; }
function runNode(args) { return new Promise((resolve) => { const child = spawn(process.execPath, args, { cwd: path.resolve(__dirname, '../../..') }); let stderr = ''; child.stderr.on('data', (chunk) => { stderr += chunk; }); child.on('close', (code) => resolve({ code, stderr })); }); }
async function removeTestLockDirectory(directory) { const entries = await fs.readdir(directory); for (const entry of entries) { const stat = await fs.lstat(path.join(directory, entry)); if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`test cleanup refused unexpected entry ${entry}`); await fs.unlink(path.join(directory, entry)); } await fs.rmdir(directory); }

test('strict generator rejects leading-zero semantic versions and tracks canonical identity', async () => { const f = await fixture(); const ledger = emptyLedger('staging', f.remote, origin); assert.throws(() => buildManifest({ environment: 'staging', ledger, type: 'available', revision: 1, publishedAt: time, origin, version: '01.2.3', versionCode: 2, minimumSupportedVersionCode: 1, sha256: 'a'.repeat(64), sizeBytes: 4, releaseNotes: 'n', requiredUpdateReason: 'r' }), /leading zero/); const disabled = buildManifest({ environment: 'staging', ledger, type: 'disabled', revision: 1, publishedAt: time, origin, reason: 'Hold.' }); assert.match(canonicalManifestIdentity(disabled), /"schemaVersion": 1/); });

test('dry run never claims activation or writes a manifest', async () => { const state = await prepared(); const result = await publishToLocalFixture(publishArgs(state, { dryRun: true })); assert.equal(result.wrote, false); assert.equal(result.receipt.activation, 'not-attempted'); await assert.rejects(fs.stat(path.join(state.remote, 'manifest.json')), /ENOENT/); });

test('repeated concurrent dry-runs and failures leave a previously empty filesystem exactly empty', async () => { const base = await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(), 'damsure-dry-'))); const root = path.join(base, 'release-root'); const ledgerPath = path.join(base, 'ledger.json'); const ledger = emptyLedger('staging', root, origin); const disabled = buildManifest({ environment: 'staging', ledger, type: 'disabled', revision: 1, publishedAt: time, origin, reason: 'Dry.' }); const dryPublish = () => publishToLocalFixture({ target: new LocalReleaseTarget(root), ledgerPath, environment: 'staging', root, origin, manifest: disabled, trustedReceiptAt: time, dryRun: true }); const results = await Promise.all([...Array(8)].map(() => reserveVersionCodeAtPath({ ledgerPath, environment: 'staging', root, origin, code: 2, dryRun: true }))); assert.equal(results.length, 8); await Promise.all([...Array(8)].map(dryPublish)); await assert.rejects(reserveVersionCodeAtPath({ ledgerPath, environment: 'staging', root, origin, code: 1, dryRun: true }), /reserved/); await assert.rejects(publishToLocalFixture({ target: new LocalReleaseTarget(root), ledgerPath, environment: 'staging', root, origin, manifest: { ...disabled, manifestRevision: 0 }, trustedReceiptAt: time, dryRun: true }), /revision/); assert.deepEqual(await fs.readdir(base), []); });

test('unprotected lock state refuses every former pathname-replacement cleanup path before mutation', async () => { const f = await fixture(); await fs.chmod(f.root, 0o755); await assert.rejects(withLedgerLock(f.ledgerPath, async () => {}), /operator-owned 0700/); await assert.rejects(recoverLedgerLock(f.ledgerPath, path.join(f.root, 'missing-receipt')), /operator-owned 0700/); assert.deepEqual(await fs.readdir(f.root), []); });

test('read-only 0500 lock state refuses before any mutation', async () => { const f = await fixture(); await fs.chmod(f.root, 0o500); await assert.rejects(withLedgerLock(f.ledgerPath, async () => {}), /operator-owned 0700/); assert.deepEqual(await fs.readdir(f.root), []); await fs.chmod(f.root, 0o700); });

test('available publication rejects text artifacts before upload', async () => { const state = await prepared(); await fs.writeFile(state.artifact, 'plain text'); await assert.rejects(publishToLocalFixture(publishArgs(state)), /APK ZIP/); await assert.rejects(fs.stat(path.join(state.remote, 'damsure-2.apk')), /ENOENT/); });

test('available publication verifies local and independently downloaded APK before activation', async () => { const state = await prepared(); const result = await publishToLocalFixture(publishArgs(state, { receiptPath: path.join(state.root, 'receipt.json') })); assert.equal(result.receipt.activation, 'active'); const ledger = await readLedger(state.ledgerPath, 'staging', state.remote, origin); assert.equal(ledger.lastManifestRevision, 1); assert.equal(ledger.receiptState.status, 'written'); assert.deepEqual(JSON.parse(await fs.readFile(path.join(state.remote, 'manifest.json'), 'utf8')), state.manifest); });

test('untrusted tool substitutions and certificate/package/version mismatches are refused', async () => { const state = await prepared(); const expected = { artifactPath: state.artifact, expectedSha256: state.sha256, expectedSizeBytes: state.sizeBytes, expectedPackageId: PACKAGE_IDS.staging, expectedVersionCode: 2, expectedVersionName: '1.0.2', expectedCertificateSha256: state.tools.stagingCertificate, toolManifestPath: state.tools.toolManifest, environment: 'staging' }; await fs.chmod(state.tools.toolManifest, 0o666); await assert.rejects(verifyApkArtifact(expected), /protected/); await fs.chmod(state.tools.toolManifest, 0o600); const symlinkParent = path.join(state.root, 'linked-tools'); await fs.symlink(state.root, symlinkParent); const linkedManifest = path.join(symlinkParent, 'tool-manifest.json'); await assert.rejects(verifyApkArtifact({ ...expected, toolManifestPath: linkedManifest }), /symlink/); await fs.appendFile(state.tools.aapt, '\n// changed'); await assert.rejects(verifyApkArtifact(expected), /hash mismatch/); });

test('journal recovers manifest-success/ledger-failure without reusing revision', async () => { const state = await prepared(); await assert.rejects(publishToLocalFixture(publishArgs(state, { hooks: { afterManifestReplaced: async () => { throw new Error('injected crash'); } } })), /injected crash/); const pending = await readLedger(state.ledgerPath, 'staging', state.remote, origin); assert.equal(pending.pendingPublication.manifestRevision, 1); await assert.rejects(publishToLocalFixture(publishArgs(state)), /pending publication/); const recovered = await recoverPublication({ target: new LocalReleaseTarget(state.remote), ledgerPath: state.ledgerPath, environment: 'staging', root: state.remote, origin }); assert.equal(recovered.receipt.phase, 'recovered'); const committed = await readLedger(state.ledgerPath, 'staging', state.remote, origin); assert.equal(committed.lastManifestRevision, 1); });

test('every pre-manifest crash burns the exact revision and requires a newer one', async () => { for (const phase of ['afterPrepared', 'afterLocalVerification', 'afterArtifactUploaded', 'afterDownloadVerification', 'beforeManifestReplace']) { const state = await prepared(); await assert.rejects(publishToLocalFixture(publishArgs(state, { hooks: { [phase]: async () => { throw new Error(phase); } } })), new RegExp(phase)); const recovered = await recoverPublication({ target: new LocalReleaseTarget(state.remote), ledgerPath: state.ledgerPath, environment: 'staging', root: state.remote, origin }); assert.equal(recovered.burned, true, phase); const ledger = await readLedger(state.ledgerPath, 'staging', state.remote, origin); assert.equal(ledger.pendingPublication, null); assert.equal(ledger.lastManifestRevision, 1); assert.equal(ledger.maxLatestVersionCode, 2); } });

test('receipt recovery recreates the exact deterministic receipt after activation', async () => { const state = await prepared(); const blocked = path.join(state.root, 'receipt-directory'); await fs.mkdir(blocked); const result = await publishToLocalFixture(publishArgs(state, { receiptPath: blocked })); assert.equal(result.receiptPending, true); const receiptPath = path.join(state.root, 'receipt.json'); const recovered = await recoverPublication({ target: new LocalReleaseTarget(state.remote), ledgerPath: state.ledgerPath, environment: 'staging', root: state.remote, origin, receiptPath }); assert.deepEqual(JSON.parse(await fs.readFile(receiptPath, 'utf8')), recovered.receipt); const ledger = await readLedger(state.ledgerPath, 'staging', state.remote, origin); assert.equal(ledger.receiptState.status, 'written'); });

test('live lock recovery fails closed and preserves the exact active owner state', async () => { const f = await fixture(); const lock = `${f.ledgerPath}.lock`; const owner = JSON.stringify({ pid: process.pid, acquiredAt: time, nonce: 'live-owner' }); await fs.mkdir(lock); await fs.writeFile(path.join(lock, 'owner.json'), owner); const receipt = path.join(f.root, 'operator-recovery.txt'); await fs.writeFile(receipt, 'operator reviewed'); await assert.rejects(recoverLedgerLock(f.ledgerPath, receipt), /currently live/); assert.equal(await fs.readFile(path.join(lock, 'owner.json'), 'utf8'), owner); await assert.rejects(withLedgerLock(f.ledgerPath, async () => {}), /recovery guard/); });

test('owner-write recovery interleaving aborts the empty lease without permanent lock or guard residue', async () => { const f = await fixture(); const receipt = path.join(f.root, 'operator-recovery.txt'); await fs.writeFile(receipt, 'reviewed'); let recovered; await assert.rejects(withLedgerLock(f.ledgerPath, async () => {}, { lockHooks: { beforeOwnerWrite: async () => { recovered = await recoverLedgerLock(f.ledgerPath, receipt); } } }), /lock state changed|ENOENT/); assert.deepEqual(recovered, { recoveredEmptyOwnerWindow: true }); assert.deepEqual((await fs.readdir(f.root)).filter((name) => name.includes('.lock') || name.includes('recovery-guard')), []); await withLedgerLock(f.ledgerPath, async () => {}); });

test('environment/root binding rejects symlinks, shared roots, and production confusion', async () => { const f = await fixture(); const linked = path.join(f.root, 'linked'); await fs.symlink(f.remote, linked); await assert.rejects(reserveVersionCodeAtPath({ ledgerPath: f.ledgerPath, environment: 'staging', root: linked, origin, code: 2 }), /symlink/); const ledger = await reserveVersionCodeAtPath({ ledgerPath: f.ledgerPath, environment: 'staging', root: f.remote, origin, code: 2 }); assert.equal(ledger.environment, 'staging'); await assert.rejects(readLedger(f.ledgerPath, 'production', f.remote, 'https://damsure.nandakrishnan.in'), /environment-confused/); });

test('concurrent first root binding permits exactly one ledger owner', async () => { const f = await fixture(); const secondLedger = path.join(f.root, 'second-ledger.json'); const results = await Promise.allSettled([reserveVersionCodeAtPath({ ledgerPath: f.ledgerPath, environment: 'staging', root: f.remote, origin, code: 2 }), reserveVersionCodeAtPath({ ledgerPath: secondLedger, environment: 'staging', root: f.remote, origin, code: 2 })]); assert.equal(results.filter((result) => result.status === 'fulfilled').length, 1); });

test('child-process lock makes same-code reservation single-winner and retains distinct codes', async () => { const f = await fixture(); const cli = path.resolve(__dirname, '../publish.cjs'); const common = ['reserve', '--environment', 'staging', '--ledger', f.ledgerPath, '--fixture-root', f.remote, '--origin', origin]; const [sameA, sameB] = await Promise.all([runNode([cli, ...common, '--version-code', '2']), runNode([cli, ...common, '--version-code', '2'])]); assert.equal([sameA.code, sameB.code].filter((code) => code === 0).length, 1); const [three, four] = await Promise.all([runNode([cli, ...common, '--version-code', '3']), runNode([cli, ...common, '--version-code', '4'])]); assert.equal(three.code, 0, three.stderr); assert.equal(four.code, 0, four.stderr); const ledger = await readLedger(f.ledgerPath, 'staging', f.remote, origin); assert.deepEqual(ledger.reservedVersionCodes, [1, 2, 3, 4]); });

test('child-process publishes with a shared revision allow exactly one canonical payload', async () => { const state = await prepared(); const cli = path.resolve(__dirname, '../publish.cjs'); const base = ['publish', '--environment', 'staging', '--ledger', state.ledgerPath, '--fixture-root', state.remote, '--origin', origin, '--type', 'available', '--revision', '1', '--published-at', time, '--receipt-at', time, '--version', '1.0.2', '--version-code', '2', '--minimum-supported-version-code', '1', '--sha256', state.sha256, '--size-bytes', String(state.sizeBytes), '--required-update-reason', 'Required.', '--artifact', state.artifact, '--tool-manifest', state.tools.toolManifest]; const [first, second] = await Promise.all([runNode([cli, ...base, '--release-notes', 'One.']), runNode([cli, ...base, '--release-notes', 'Two.'])]); assert.equal([first.code, second.code].filter((code) => code === 0).length, 1); const ledger = await readLedger(state.ledgerPath, 'staging', state.remote, origin); assert.equal(ledger.lastManifestRevision, 1); assert.equal(Object.keys(ledger.manifests).length, 1); });

test('recovery compares the complete strict manifest and permits only canonical field reordering', async () => { const state = await prepared(); await assert.rejects(publishToLocalFixture(publishArgs(state, { hooks: { afterManifestReplaced: async () => { throw new Error('crash'); } } }))); const manifestPath = path.join(state.remote, 'manifest.json'); const original = JSON.parse(await fs.readFile(manifestPath, 'utf8')); await fs.writeFile(manifestPath, JSON.stringify({ ...original, attacker: true })); await assert.rejects(recoverPublication({ target: new LocalReleaseTarget(state.remote), ledgerPath: state.ledgerPath, environment: 'staging', root: state.remote, origin }), /unknown|identity/); delete original.requiredUpdateReason; await fs.writeFile(manifestPath, JSON.stringify(original)); await assert.rejects(recoverPublication({ target: new LocalReleaseTarget(state.remote), ledgerPath: state.ledgerPath, environment: 'staging', root: state.remote, origin }), /unknown|identity/); const reordered = Object.fromEntries(Object.entries(state.manifest).reverse()); await fs.writeFile(manifestPath, JSON.stringify(reordered)); const recovered = await recoverPublication({ target: new LocalReleaseTarget(state.remote), ledgerPath: state.ledgerPath, environment: 'staging', root: state.remote, origin }); assert.equal(recovered.recovered, true); });

test('certificate fingerprints require distinct exact SHA-256 values', async () => { const state = await prepared(); const tool = JSON.parse(await fs.readFile(state.tools.toolManifest, 'utf8')); tool.certificates.staging = 'AA'; await fs.writeFile(state.tools.toolManifest, JSON.stringify(tool), { mode: 0o600 }); await assert.rejects(verifyApkArtifact({ artifactPath: state.artifact, expectedSha256: state.sha256, expectedSizeBytes: state.sizeBytes, expectedPackageId: PACKAGE_IDS.staging, expectedVersionCode: 2, expectedVersionName: '1.0.2', expectedCertificateSha256: state.tools.stagingCertificate, toolManifestPath: state.tools.toolManifest, environment: 'staging' }), /exactly 64/); tool.certificates.staging = state.tools.productionCertificate; await fs.writeFile(state.tools.toolManifest, JSON.stringify(tool), { mode: 0o600 }); await assert.rejects(verifyApkArtifact({ artifactPath: state.artifact, expectedSha256: state.sha256, expectedSizeBytes: state.sizeBytes, expectedPackageId: PACKAGE_IDS.staging, expectedVersionCode: 2, expectedVersionName: '1.0.2', expectedCertificateSha256: state.tools.stagingCertificate, toolManifestPath: state.tools.toolManifest, environment: 'staging' }), /distinct/); });

test('artifact parent symlinks and source replacement after verification fail closed', async () => { const state = await prepared(); const parent = path.join(state.root, 'artifact-link'); await fs.symlink(state.root, parent); await assert.rejects(basicArtifactMetadata(path.join(parent, 'candidate.apk'), { requireApkZip: true }), /symlink/); await assert.rejects(publishToLocalFixture(publishArgs(state, { hooks: { afterLocalVerification: async () => { await fs.writeFile(state.artifact, 'replacement'); } } })), /APK ZIP|SHA-256/); await assert.rejects(fs.stat(path.join(state.remote, 'damsure-2.apk')), /ENOENT/); });

test('recovery guard leaves an empty or owned successor byte-for-byte untouched', async () => { for (const successorOwner of [null, { pid: 999998, acquiredAt: time, nonce: 'successor' }]) { const f = await fixture(); const lock = `${f.ledgerPath}.lock`; const receipt = path.join(f.root, 'operator-recovery.txt'); await fs.writeFile(receipt, 'reviewed'); await fs.mkdir(lock); await fs.writeFile(path.join(lock, 'owner.json'), JSON.stringify({ pid: 999999, acquiredAt: time, nonce: 'dead-owner' })); await assert.rejects(recoverLedgerLock(f.ledgerPath, receipt, { hooks: { beforeRecoveryClaim: async () => { await fs.rename(lock, `${lock}.old`); await fs.mkdir(lock); if (successorOwner) await fs.writeFile(path.join(lock, 'owner.json'), JSON.stringify(successorOwner)); } } }), /manual recovery/); const finalOwner = successorOwner ? await fs.readFile(path.join(lock, 'owner.json'), 'utf8') : null; assert.equal(finalOwner, successorOwner ? JSON.stringify(successorOwner) : null); assert.ok(await fs.lstat(`${f.ledgerPath}.recovery-guard.json`)); } });

test('claim cleanup never recursively deletes a victim substituted after verification', async () => { const f = await fixture(); let victim; await assert.rejects(withLedgerLock(f.ledgerPath, async () => {}, { lockHooks: { beforeMetadataClaim: async (claim) => { const original = `${claim}.original`; await fs.rename(claim, original); await fs.mkdir(claim); await fs.writeFile(path.join(claim, 'owner.json'), await fs.readFile(path.join(original, 'owner.json'))); await fs.writeFile(path.join(claim, 'victim.txt'), 'do-not-delete'); victim = claim; } } }), /changed/); assert.equal(await fs.readFile(path.join(victim, 'victim.txt'), 'utf8'), 'do-not-delete'); assert.equal((await fs.readdir(victim)).sort().join(','), 'owner.json,victim.txt'); });

test('guard resolution requires the exact nonce and acknowledgement, then clears a dead lease', async () => { const f = await fixture(); const lock = `${f.ledgerPath}.lock`; const receipt = path.join(f.root, 'operator-recovery.txt'); await fs.writeFile(receipt, 'reviewed'); await fs.mkdir(lock); await fs.writeFile(path.join(lock, 'owner.json'), JSON.stringify({ pid: 999999, acquiredAt: time, nonce: 'dead-owner' })); await assert.rejects(recoverLedgerLock(f.ledgerPath, receipt, { hooks: { afterRecoveryClaim: async () => { throw new Error('retain'); } } }), /retain/); const guardPath = `${f.ledgerPath}.recovery-guard.json`; const guard = JSON.parse(await fs.readFile(guardPath, 'utf8')); await assert.rejects(resolveRecoveryGuard({ ledgerPath: f.ledgerPath, guardNonce: 'wrong', acknowledgement: 'RESOLVE-RECOVERY-GUARD' }), /token/); await assert.rejects(resolveRecoveryGuard({ ledgerPath: f.ledgerPath, guardNonce: guard.nonce, acknowledgement: 'wrong' }), /acknowledge/); const result = await resolveRecoveryGuard({ ledgerPath: f.ledgerPath, guardNonce: guard.nonce, acknowledgement: 'RESOLVE-RECOVERY-GUARD' }); assert.equal(result.resolved, true); await assert.rejects(fs.lstat(lock), /ENOENT/); await assert.rejects(fs.lstat(guardPath), /ENOENT/); });

test('guard resolution refuses a live quarantined publisher', async () => { const f = await fixture(); const lock = `${f.ledgerPath}.lock`; const receipt = path.join(f.root, 'operator-recovery.txt'); await fs.writeFile(receipt, 'reviewed'); await fs.mkdir(lock); await fs.writeFile(path.join(lock, 'owner.json'), JSON.stringify({ pid: process.pid, acquiredAt: time, nonce: 'live-owner' })); await assert.rejects(recoverLedgerLock(f.ledgerPath, receipt), /currently live/); const guard = JSON.parse(await fs.readFile(`${f.ledgerPath}.recovery-guard.json`, 'utf8')); await assert.rejects(resolveRecoveryGuard({ ledgerPath: f.ledgerPath, guardNonce: guard.nonce, acknowledgement: 'RESOLVE-RECOVERY-GUARD' }), /publisher is live/); });
